fix: true
parallel: true
ruby_version: 2.7

ignore:
  - 'vendor/**/*'
  - 'spec/**/*':
    # There are some false hits when doing repeated
    # Class.new blocks in different test cases
    - Lint/DuplicateMethods
    # We define a lot of test-specific classes within our test blocks
    # There's probably a better way to do this, but it's not worth the
    # effort right now, so let's just disable for specs
    - Lint/ConstantDefinitionInBlock
