sudo: false
language: ruby
rvm:
- 2.5
- 2.6
- 2.7
gemfile:
  - Gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_5_0_graphiti_rails.gemfile
  - gemfiles/rails_5_1_graphiti_rails.gemfile
  - gemfiles/rails_5_2_graphiti_rails.gemfile
  - gemfiles/rails_6_graphiti_rails.gemfile
env:
  - COMMAND="standardrb --no-fix --format progress"
  - COMMAND=rspec
  - COMMAND=rspec APPRAISAL_INITIALIZED=true
matrix:
  exclude:
    # Don't run the appraisal version of the specs for the base gemfile
    - env: COMMAND=rspec APPRAISAL_INITIALIZED=true
      gemfile: Gemfile
    # Don't run the standardrb check on any gemfile except the base gemfile
    # (but run it for each ruby version)
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_4.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_0.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_1.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_2.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_6.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_0_graphiti_rails.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_1_graphiti_rails.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_5_2_graphiti_rails.gemfile
    - env: COMMAND="standardrb --no-fix --format progress"
      gemfile: gemfiles/rails_6_graphiti_rails.gemfile
    # Don't run the basic versions of the specs for any of the specific gemfiles
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_4.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_0.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_1.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_2.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_6.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_0_graphiti_rails.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_1_graphiti_rails.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_5_2_graphiti_rails.gemfile
    - env: COMMAND=rspec
      gemfile: gemfiles/rails_6_graphiti_rails.gemfile

    # Don't run rails 4 egmfile against any rubies (for some reason?)
    - gemfile: gemfiles/rails_4.gemfile
      rvm: 2.5
    - gemfile: gemfiles/rails_4.gemfile
      rvm: 2.6
    - gemfile: gemfiles/rails_4.gemfile
      rvm: 2.7

script:
  - bundle _1.17.3_ exec $COMMAND

install: bundle _1.17.3_ install --retry=3 --jobs=3
before_install:
- gem install bundler -v '1.17.3'
deploy:
  provider: rubygems
  api_key:
    secure: aON6EPWgHZXVQs+n/glMjPJ5kMpeR25khDpYlFIM0Ggf2+xuT/yRMtGbNTYnB01v/v2s9tNWK6QlMGARCbKz/W6WS8VNwFxs4DO1IPY3XoyF8QaPlXVKfBLldjUoVx61zL5xtcv8uZqWT1ATY+DjHW3nQ875ss/GW8tw+UASG1uUEuPCE9z+rNa3xYnm2qSZOwhFWqs5bHRQcc3gF3O8Hy8r4aosYTAlYOSeGDToqTUq1Ws21dV4xnIo97Nhmh9SYBQcKpZk1qF9bUz4zqdKsDKAxHMJRShtILmhPxNpIqE5ZV0+Xt+cnwi11AZDhSgfoUqYO9t2uG562luAqTnEZEQl+Lmc+nx4nJTH6tcR3ri301k0O+qDZ3PgSojJvrUuNC8DDLbbsVJNHYycGOLclqQq1aNbgz9HayEE5s+AyklPcprJhngxA5WP80AtONAxxLt4OjrY0X80TvOi2b5nfIN7DowGmcLbRahnms98Yk6/i1vCNV4R9bO0AaqpGLV+L8sVp98Qquk2mpvB3Le4W89qm5int1y2FNJbgInBpY1UOsI3wLENt0npC1X/KVMJKkpHvk80rGccI5FIVRUDZ3YD77hi+s1busPSVQ/+l4QdTFHmWp13Pghf6hNaIwfNwFMHwM2Fkv8YXa4c1mWc1cY5WP1ELS8cEnjtmp/9Iuc=
  gem: graphiti
  on:
    tags: true
    repo: graphiti-api/graphiti
