/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'intro',
    'getting-started/installation',
    'concepts/overview',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'concepts/resources',
        'concepts/relationships',
        'concepts/persisting',
        'concepts/endpoints',
        'concepts/links',
      ],
    },
    {
      type: 'category',
      label: 'Topics',
      items: [
        'topics/authorization',
        'topics/error-handling',
        'topics/testing',
        'topics/debugging',
        'topics/caching',
        'topics/etags',
        'topics/json-attributes',
        'topics/remote-resources',
        'concepts/backends-and-models',
        'topics/without-activerecord',
        'topics/openstruct-models',
        'topics/customizing-sideloads',
        'topics/hopping-relationships',
      ],
    },
    {
      type: 'category',
      label: 'JavaScript Client',
      items: [
        'js/index',
        'js/installation',
        'js/models',
        'js/reads',
        'js/writes',
        'js/middleware',
        'js/authentication',
        'js/state-syncing',
        'js/ddau',
        'js/extra-params',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      link: {type: 'doc', id: 'tutorial/index'},
      items: [
        'getting-started/first-api',
        'tutorial/step_0',
        'tutorial/step_1',
        'tutorial/step_2',
        'tutorial/step_3',
        'tutorial/step_4',
        'tutorial/step_5',
        'tutorial/step_6',
        'tutorial/step_7',
        'tutorial/step_8',
        'tutorial/step_9',
      ],
    },
    {
      type: 'category',
      label: 'More',
      items: [
        'reference/upgrading-2-0',
        'reference/vandal',
        'reference/why',
      ],
    },
  ],
};
